name: Update Doxygen Docs

on:
  push:
    branches:
      - main

jobs:
  generate-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: リポジトリをチェックアウト
        uses: actions/checkout@v4

      - name: Doxygenをインストール
        run: sudo apt-get install -y doxygen graphviz

      - name: Doxygenドキュメントを生成
        run: doxygen Doxyfile

      - name: gh-pagesブランチにデプロイ
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./docs/html
